version: 2.1

commands:
  install_tox:
    steps:
      - run: pip install tox

  run_tox:
    parameters:
      env:
        default: "py36"
        type: string
    steps:
      - run: tox --recreate -e <<parameters.env>>

jobs:
  test_py36:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - install_tox
      - run_tox:
          env: "py36"

  test_py37:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - install_tox
      - run_tox:
          env: "py37"

  test_py38:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - install_tox
      - run_tox:
          env: "py38"

  test_py39:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - install_tox
      - run_tox:
          env: "py39"

workflows:
  main:
    jobs:
      - test_py36
      - test_py37
      - test_py38
      - test_py39
