name: Publish to PyPI

on:
  push:
    tags:
      - 'spiffe-*'
      - 'spiffe-tls-*'

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Set up uv
        uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7.3.0
        with:
          enable-cache: true

      - name: Install Python
        run: uv python install 3.10

      # Conditional step for spiffe module
      - name: Publish spiffe
        if: startsWith(github.ref, 'refs/tags/spiffe-') && !startsWith(github.ref, 'refs/tags/spiffe-tls-')
        run: |
          cd spiffe
          make build
          uv publish

      # Conditional step for spiffe-tls module
      - name: Publish spiffe-tls
        if: startsWith(github.ref, 'refs/tags/spiffe-tls-')
        run: |
          cd spiffe-tls
          make build
          uv publish
