name: Publish to PyPI

on:
  push:
    tags:
      - 'spiffe-*'
      - 'spiffe-tls-*'

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.9'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      # Conditional step for spiffe module
      - name: Publish spiffe
        if: startsWith(github.ref, 'refs/tags/spiffe-') && !startsWith(github.ref, 'refs/tags/spiffe-tls-')
        run: |
          cd spiffe
          make build
          poetry publish 

      # Conditional step for spiffe-tls module
      - name: Publish spiffe-tls
        if: startsWith(github.ref, 'refs/tags/spiffe-tls-')
        run: |
          cd spiffe-tls
          make build
          poetry publish 
